### ISSUE TITLE
Unable to start mapping on Safari

### ISSUE THREAD

**Issue by sarahmamy** [pelica-labs/pelica#110]
Steps to reproduce
* Open Pelica on Safari
* Click on Start Mapping, it will open a map but you do not see the edition tools

I have also tried creating a map from "my maps" and could not see the map editor

---

My sister reported that she could not map on her iPhone on Safari. I don't know if it is the same or another bug

**Comment by bstnfrmry** [comment]
Caused by https://github.com/pelica-labs/pelica/issues/86
